var searchData=
[
  ['magazine_60',['Magazine',['../class_online___book___store__v2_1_1_magazine.html',1,'Online_Book_Store_v2.Magazine'],['../class_online___book___store__v2_1_1_magazine_panel.html#a14704d522d1724bb839b87eb8674f8d9',1,'Online_Book_Store_v2.MagazinePanel.magazine()']]],
  ['magazine_2ecs_61',['Magazine.cs',['../_magazine_8cs.html',1,'']]],
  ['magazinedetailsform_62',['MagazineDetailsForm',['../class_online___book___store__v2_1_1_magazine_details_form.html',1,'Online_Book_Store_v2.MagazineDetailsForm'],['../class_online___book___store__v2_1_1_magazine_details_form.html#a7ee07d543c91de19a16bbcad32eecb21',1,'Online_Book_Store_v2.MagazineDetailsForm.MagazineDetailsForm()']]],
  ['magazinedetailsform_2ecs_63',['MagazineDetailsForm.cs',['../_magazine_details_form_8cs.html',1,'']]],
  ['magazinedetailsform_2edesigner_2ecs_64',['MagazineDetailsForm.Designer.cs',['../_magazine_details_form_8_designer_8cs.html',1,'']]],
  ['magazineloader_65',['MagazineLoader',['../class_online___book___store__v2_1_1_data_base.html#a74b05dd27a7cec2b3d6252cef41b2a65',1,'Online_Book_Store_v2::DataBase']]],
  ['magazinepanel_66',['MagazinePanel',['../class_online___book___store__v2_1_1_magazine_panel.html',1,'Online_Book_Store_v2.MagazinePanel'],['../class_online___book___store__v2_1_1_magazine_panel.html#a92c9ebffe1fa73adbaee7c9afd4f9aec',1,'Online_Book_Store_v2.MagazinePanel.MagazinePanel()']]],
  ['magazinepanel_2ecs_67',['MagazinePanel.cs',['../_magazine_panel_8cs.html',1,'']]],
  ['magnifier_68',['magnifier',['../class_online___book___store__v2_1_1_product_panel.html#a202b92c1f0c42063d4f03ca0eabf89c9',1,'Online_Book_Store_v2::ProductPanel']]],
  ['mainform_69',['MainForm',['../class_online___book___store__v2_1_1_main_form.html',1,'Online_Book_Store_v2.MainForm'],['../class_online___book___store__v2_1_1_main_form.html#a65a05cc2f6750e1de6a2d4cae6da4910',1,'Online_Book_Store_v2.MainForm.MainForm()']]],
  ['mainform_2ecs_70',['MainForm.cs',['../_main_form_8cs.html',1,'']]],
  ['mainform_2edesigner_2ecs_71',['MainForm.Designer.cs',['../_main_form_8_designer_8cs.html',1,'']]],
  ['musiccd_72',['MusicCD',['../class_online___book___store__v2_1_1_music_c_d.html',1,'Online_Book_Store_v2.MusicCD'],['../class_online___book___store__v2_1_1_music_c_d_panel.html#a6b39d845b7123731ca879ca0e9373ef1',1,'Online_Book_Store_v2.MusicCDPanel.musicCD()']]],
  ['musiccd_2ecs_73',['MusicCD.cs',['../_music_c_d_8cs.html',1,'']]],
  ['musiccddetailsform_74',['MusicCDDetailsForm',['../class_online___book___store__v2_1_1_music_c_d_details_form.html',1,'Online_Book_Store_v2.MusicCDDetailsForm'],['../class_online___book___store__v2_1_1_music_c_d_details_form.html#a12e3610984a6dde259e165b19138b8a9',1,'Online_Book_Store_v2.MusicCDDetailsForm.MusicCDDetailsForm()']]],
  ['musiccddetailsform_2ecs_75',['MusicCDDetailsForm.cs',['../_music_c_d_details_form_8cs.html',1,'']]],
  ['musiccddetailsform_2edesigner_2ecs_76',['MusicCDDetailsForm.Designer.cs',['../_music_c_d_details_form_8_designer_8cs.html',1,'']]],
  ['musiccdloader_77',['MusicCDLoader',['../class_online___book___store__v2_1_1_data_base.html#ade59bd9c1f613dbbbab0edc93214ed14',1,'Online_Book_Store_v2::DataBase']]],
  ['musiccdpanel_78',['MusicCDPanel',['../class_online___book___store__v2_1_1_music_c_d_panel.html',1,'Online_Book_Store_v2.MusicCDPanel'],['../class_online___book___store__v2_1_1_music_c_d_panel.html#a1e3f56c8617508d05edac1dcba33c5c3',1,'Online_Book_Store_v2.MusicCDPanel.MusicCDPanel()']]],
  ['musiccdpanel_2ecs_79',['MusicCDPanel.cs',['../_music_c_d_panel_8cs.html',1,'']]]
];
